Migrated to nextcord and added thread support
MenuDocs/Pyro pull request #41
Opened 2021-10-13 15:03 UTC by Auxtal

Pyro will now automatically join any threads created in any python support channels. It is also now running on the latest version of nextcord as of me making this pull request (2.0.0a3). 

I have also updated the readme to use a more efficient command for deploying on docker. I have tested the thread joining and some commands and all seems to work well on nextcord.

The `buttons` lib works fine with nextcord as of now. If anyone wants to do some more testing of commands with the bot running on nextcord feel free.

My auto code formatter black also updated some of the command decorators.

2021-10-13 15:17 UTC, i-am-zaidali commented
Two queries
1. Why aren't we using bot_base here?
2. Not really a query, but for ease of transferring to nextcord I was planning to change imports as such: `import nextcord as discord` :joy:

2021-10-14 01:45 UTC, Skelmis requested changes

2021-10-14 01:45 UTC, Skelmis commented on cogs/menudocs.py
> +        if not thread.parent_id in PYTHON_HELP_CHANNEL_IDS:
``thread.parent_id not in ..``, just makes it a little easier to read.

2021-10-14 01:49 UTC, Skelmis commented
> Two queries
> 
>     1. Why aren't we using bot_base here?

Little out of scope for this pr, however I could be keen to implement it in another pr.

2021-10-14 12:35 UTC, merged