feat: :sparkles: Added format command
MenuDocs/Pyro pull request #47
Opened 2022-01-11 13:03 UTC by Auxtal

Basically I am sick and tired of people saying "pls help me"... hence this

2022-01-11 13:04 UTC, Auxtal commented
Totally didn't copy the check list from nextcord 👉👈

2022-01-13 09:00 UTC, Skelmis requested changes

2022-01-13 09:00 UTC, Skelmis commented on cogs/menudocs.py
> +        await ctx.send(embed=embed)
Care to add a check which checks if ctx.message is a reply to someone else, then Pyro can also reply to that message. In a sense pinging them?

2022-01-15 04:34 UTC, Skelmis approved these changes

2022-01-15 04:34 UTC, merged